#!/bin/env bash

# Install the prompt configure files for Starship and Bash.

helpMe="$(cat <<EOF
Usage: install [OPTION]...
Usage: install <distro> [-p <password>] [-y]

Options:
	--root				Install for Debian based distros.
	-y | --yes			Answer yes to all questions.
	-p | --password		Set the password for the root user.
	-h | --help			Show this help message.
EOF
)"

# If the script was executed with sudo command then the user will be root, but still need the name of the user
# to install the config files for that user, so get the name of the user from the SUDO_USER variable.

# Use case statement to check for arguments.
while true ; do case "${1}" in
	--root				 )

		# Check if the user is root.
		if test "$(whoami)" = "root" ; then
			# Check if the user is root.
			echo "This script must be run as root." ; exit 1
		else
			installRoot="true" ; shift
		fi
	;;
	-y | --yes			 ) answerYes="true" ; shift ;;
	-p | --password		 ) rootPassword="${2}" ; shift 2 ;;
	-h | --help			 ) echo "${helpMe}" ; exit 0 ;;
esac ; if test -z "${1}" ; then break ; fi ; done

# Copy all .* files to the home directory, but exlude the `.` and `..` directories.
cd Linux || exit 1

for file in .* ; do
	if test "${file}" != "." && test "${file}" != ".." ; then
		if test "${installRoot}" = "true" && test -n "${rootPassword}" ; then
			if test "${answerYes}" = "yes" ; then
				echo "${rootPassword}" | sudo -S cp -rvf "${file}" /root/
			else
				cp -rvf "${file}" /root/
			fi
		fi
		cp -rvf "${file}" ~/
	fi
done

exit 0
