#!/bin/env bash


docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    -e TZ="America/Boise" \
    -v "$(pwd)/etc-pihole/:/etc/pihole/" \
    -v "$(pwd)/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --restart=unless-stopped \
    thenetworkchuck/networkchuck_pihole

docker run -d \
    --name=pihole-unbound \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    -e TZ="America/Boise" \
    -e WEBPASSWORD='3kbfRytxxAB?' `#better to use single quotes` \
    -v "$(pwd)/docker/pihole-unbound/etc-pihole/:/etc/pihole/" \
    -v "$(pwd)/docker/pihole-unbound/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --restart=unless-stopped \
  rlabinc/pihole-unbound:latest