# ~/.config/starship.toml
# This is my starship.toml file for my personal computer at home running KDE Neon and/or Windows 10/11.
# feel free to use it as a template for your own starship.toml file if you like it or the color purple.
# Using 256bit colors in the terminal:
# - Purple: 127
# - Ligth: 225
# Text styles is always bold.
[line_break]
disabled = true                                                 # Stop allowing a divided prompt
add_newline = false                                             # Do not add new line after command completion.
format = """
($username$hostname)
[$directory]
($git_branch$git_status)
$character
"""

# These are overridden by STARSHIP_LOG="error" in my .bashrc file.
scan_timeout = 2_000                                            # 2 seconds to scan timeout.
command_timeout = 2_000                                         # 2 seconds to command timeout.

# The default prompt symbol is "❯". I don't like it so I changed it to .
[character]
success_symbol = ">"                                            # Normal symbol for the prompt.
error_symbol = ">[!](fg:127)"                                   # Error symbol for the prompt.
vicmd_symbol = ">"                                              # Vi command mode symbol for the prompt.
format = " $symbol "

# Even if disabled, VSCode will still show for the first command ran in the terminal after opening.
[cmd_duration]
disabled = true                                                 # Disable the command execution time.

# Disable the container module.
[container]
disabled = true                                                 # Disable the container module.

# The directory module is enabled by default but I changed the format. The text is
# purple and bold, and the symbol is  for the home directory. For root or read
# only the symbol is 󰃖.
[directory]
disabled = false
read_only = " <ro> "
home_symbol = " <home> "
style = "bold fg:127"
read_only_style = "bold fg:127"
truncation_length = 1
format = " [in](bold fg:#FBD8FD) [$path]($style)[$read_only]($read_only_style)$home_symbol"

# Git Branch name is very useful, but sometimes the name is too long. A truncated name is a
# good sign that the branch name needs work.
[git_branch]
always_show_remote = false                                      # Do not show remote branch
style = "bold fg:127"                                           # Text color.
symbol = " [git] "                                              # Git symbol.
truncation_length = 15                                          # Shorten long branch names.
truncation_symbol = "..."
only_attached = false                                           # Not attached is not an error, so show branch name.
format = "[$symbol]($style) [$branch](bold fg:225)"

[git_status]
disabled = false                                                # Never disable the git status module.
style = "bold fg:127"                                           # Dark Magenta color.
conflicted = " (conflict)"                                      # Branch in conflict.
ahead = " (ahead)"                                              # Branch is ahead by one or more commits.
behind = " (behind)"                                            # Branch is behind by one or more commits.
diverged = " (div)"                                             # Current branch has diverged.
up_to_date = " (current)"                                       # Up-to-date.
untracked = " (untracked)"                                      # Untracked changes.
staged = " (staged)"                                            # Staged changes.
modified = " (modified)"                                        # Modified files.
renamed = " (renamed)"                                          # Renamed files.
deleted = " (deleted)"                                          # Deleted files.
format = "[$all_status$ahead_behind]($style) "

# The only reason to have the hostname in the prompt is to know if I'm ssh'd into a remote host.
[hostname]
ssh_only = true                                                 # Show only when ssh'd into remote host.
trim_at = ''                                                    # Don't trim the hostname.
style = "bold fg:#FBD8FD bg:127"                                # highlight.
format = "[@ssh:$hostname]($style)"

[nodejs]
disabled = true                                                 # Disable nodejs version and icon.

[package]
disabled = true                                                 # Disable package version and icon.

[python]
disabled = true                                                 # Disable python version and icon.

[rust]
disabled = true                                                 # Disable rust version and icon.

[ruby]
disabled = true                                                 # Disable ruby version and icon

[time]
disabled = true                                                 # Disable clock in prompt.

[username]
show_always = true                                              # Yes show who I am.
disabled = false
style_user = "bold fg:225 bg:127"                               # Highlight.
style_root = "bold fg:127 bg:225"                               # Highlight with lighter color.
format = "[$user]($style)"
